<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Image dimension should be less or equal {width}x{height}' => '',
  'Image dimension should be {width}x{height}' => '',
  'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => '',
  'The file "{file}" is either small or large. Its size should be {limit} kilo bytes.' => '',
  'Your request is invalid.' => '',
  '{attribute} cannot be blank.' => '',
  '{controller} cannot find the requested view "{view}".' => '',
  '{widget} cannot find the view "{view}".' => '',
);
